version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "631:6311" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "host" 